import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | VidText AI',
  description: 'Read the Terms of Service for VidText AI — your YouTube transcript and AI content platform.',
  alternates: { canonical: 'https://www.vidtextai.com/terms' },
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-500">Last updated: May 15, 2026</p>

      <div className="mt-8 space-y-8 text-gray-600 leading-relaxed">

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using VidText AI at <strong>www.vidtextai.com</strong>, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">2. Description of Services</h2>
          <p>VidText AI provides AI-powered tools to convert YouTube video content into:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Full timestamped transcripts</li>
            <li>AI-generated summaries</li>
            <li>SEO-optimized blog posts</li>
            <li>Structured study notes</li>
            <li>Short-form video scripts (Shorts/TikTok/Reels)</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">3. Free Tier & Usage Limits</h2>
          <p>Free users receive <strong>3 AI content generations per day</strong>. This limit resets at midnight UTC. We reserve the right to modify these limits at any time with reasonable notice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">4. Acceptable Use</h2>
          <p>You agree NOT to use VidText AI to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Process copyrighted content without proper authorization</li>
            <li>Generate content that is harmful, illegal, defamatory, or misleading</li>
            <li>Attempt to circumvent rate limits through automated means</li>
            <li>Reverse engineer, scrape, or abuse our API</li>
            <li>Use the service for any illegal purpose</li>
            <li>Resell or redistribute our AI-generated outputs as your own product</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">5. YouTube Content & Copyright</h2>
          <p>VidText AI processes publicly available YouTube videos. You are responsible for ensuring you have the right to process any video content through our service. We do not host, store, or redistribute YouTube videos. Transcripts are derived from publicly available caption data.</p>
          <p className="mt-2">All YouTube content remains subject to YouTube&apos;s Terms of Service and applicable copyright law. VidText AI is not affiliated with YouTube or Google LLC.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">6. AI-Generated Content Disclaimer</h2>
          <p>Content generated by our AI tools is provided for informational and creative purposes only. We do not guarantee the accuracy, completeness, or fitness for any particular purpose of AI-generated content. You should review and verify all AI outputs before publishing or relying on them.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">7. Intellectual Property</h2>
          <p>You retain ownership of any content you submit. AI-generated outputs based on your inputs are yours to use, subject to applicable law. VidText AI retains all rights to our platform, technology, brand, and original content.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">8. Limitation of Liability</h2>
          <p>VidText AI is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of our services, including but not limited to loss of data or revenue.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">9. Service Availability</h2>
          <p>We strive to maintain high availability but do not guarantee uninterrupted service. We may modify, suspend, or discontinue any part of our services at any time with or without notice.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">10. Changes to Terms</h2>
          <p>We may revise these Terms at any time. Continued use of our services after changes are posted constitutes your acceptance of the revised Terms. We recommend checking this page periodically.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-3">11. Contact</h2>
          <div className="rounded-lg bg-gray-50 p-4 text-sm">
            <p><strong>VidText AI</strong></p>
            <p>Email: support@vidtextai.com</p>
            <p>Website: www.vidtextai.com</p>
          </div>
        </section>

      </div>
    </div>
  )
}
